### ISSUE TITLE
NESTML implementation of `hh_psc_alpha` neuron does not reproduce NEST implementation

### ISSUE THREAD

**Issue by mschmidt87** [nest/nestml#378] opened 2017-09-14 14:16 UTC
I want to make some tests with the Hodgkin-Huxley neuron model using NESTML and therefore looked at the NESTML implementation available in the repository.
I noticed that there are two different implementations, `hh_psc_alpha.nestml` and `hh_psc_alpha_implicit.nestml`.
A simple comparison with the original implementation in the NEST master revealed that only the implicit version reproduces the behavior of the original implementation.
I attached a small reproducer script and the produced plot. The script expects the nestml models to be encapsulated in a module called `hh_psc_alpha_nestml`. Just rename the script from `*.txt` to `*.py`.
[hh_simple_test.pdf](https://github.com/nest/nestml/files/1303282/hh_simple_test.pdf)
[hh_simple_test.txt](https://github.com/nest/nestml/files/1303290/hh_simple_test.txt)

Is this a known behavior? The difference seems to be in the calculation of synaptic input currents in the model. Do you know, why only the implicit version reproduces the original behavior?
Shouldn't this be at least marked in the file?

**Comment by DimitriPlotnikov** [comment] 2017-10-06 15:13
Hi,

I'm working with the current version from master and cannot reproduce the erroneous behavior:
[hh_simple_test.pdf](https://github.com/nest/nestml/files/1363096/hh_simple_test.pdf)
[hh_tester.txt](https://github.com/nest/nestml/files/1363104/hh_tester.txt)



I were using the models from the `hh_psc_alpha.nestml` file from the `models` folder.

**Comment by mschmidt87** [comment] 2017-10-07 02:39
Hi, I tried to compile the newest master version, but failed with the following errors:
Results :

Tests in error: 
  testCodegenerationModels(org.nest.nestml._cocos.NestmlCoCosManagerTest): No value present
  testJsonOutput(org.nest.frontend.NestmlFrontendTest): No value present
  testModelsFolder(org.nest.frontend.NestmlFrontendTest): No value present
  testDryRun(org.nest.frontend.NestmlFrontendTest): No value present

Tests run: 109, Failures: 0, Errors: 4, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:07 min
[INFO] Finished at: 2017-10-07T11:36:59+09:00
[INFO] Final Memory: 65M/1072M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project nestml-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/schmidt/opt/nest/nestml/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Hier ein paar Details von den fehlgeschlagenen Tests:
Tests run: 9, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 33.127 sec <<< FAILURE!
testJsonOutput(org.nest.frontend.NestmlFrontendTest)  Time elapsed: 0.85 sec  <<< ERROR!
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.nest.nestml._symboltable.NESTMLSymbolTableCreator.visit(NESTMLSymbolTableCreator.java:280)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:984)
	at org.nest.nestml._ast.ASTInputLine.accept(ASTInputLine.java:87)
	at org.nest.nestml._visitor.NESTMLVisitor.traverse(NESTMLVisitor.java:971)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:954)
	at org.nest.nestml._ast.ASTInputBlock.accept(ASTInputBlock.java:73)
	at org.nest.nestml._visitor.NESTMLVisitor.traverse(NESTMLVisitor.java:826)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:791)
	at org.nest.nestml._ast.ASTNeuronTOP.accept(ASTNeuronTOP.java:120)
	at org.nest.nestml._visitor.NESTMLVisitor.traverse(NESTMLVisitor.java:111)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:97)
	at org.nest.nestml._ast.ASTNESTMLCompilationUnitTOP.accept(ASTNESTMLCompilationUnitTOP.java:64)
	at org.nest.nestml._symboltable.NESTMLSymbolTableCreator.createFromAST(NESTMLSymbolTableCreator.java:66)
	at org.nest.nestml._symboltable.NESTMLScopeCreator.runSymbolTableCreator(NESTMLScopeCreator.java:53)
	at org.nest.frontend.CliConfigurationExecutor.processNestmlModels(CliConfigurationExecutor.java:160)
	at org.nest.frontend.CliConfigurationExecutor.execute(CliConfigurationExecutor.java:71)
	at org.nest.frontend.NestmlFrontend.executeConfiguration(NestmlFrontend.java:359)
	at org.nest.frontend.NestmlFrontend.start(NestmlFrontend.java:122)
	at org.nest.frontend.NestmlFrontendTest.testJsonOutput(NestmlFrontendTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testModelsFolder(org.nest.frontend.NestmlFrontendTest)  Time elapsed: 0.742 sec  <<< ERROR!
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.nest.nestml._symboltable.NESTMLSymbolTableCreator.visit(NESTMLSymbolTableCreator.java:280)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:984)
	at org.nest.nestml._ast.ASTInputLine.accept(ASTInputLine.java:87)
	at org.nest.nestml._visitor.NESTMLVisitor.traverse(NESTMLVisitor.java:971)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:954)
	at org.nest.nestml._ast.ASTInputBlock.accept(ASTInputBlock.java:73)
	at org.nest.nestml._visitor.NESTMLVisitor.traverse(NESTMLVisitor.java:826)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:791)
	at org.nest.nestml._ast.ASTNeuronTOP.accept(ASTNeuronTOP.java:120)
	at org.nest.nestml._visitor.NESTMLVisitor.traverse(NESTMLVisitor.java:111)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:97)
	at org.nest.nestml._ast.ASTNESTMLCompilationUnitTOP.accept(ASTNESTMLCompilationUnitTOP.java:64)
	at org.nest.nestml._symboltable.NESTMLSymbolTableCreator.createFromAST(NESTMLSymbolTableCreator.java:66)
	at org.nest.nestml._symboltable.NESTMLScopeCreator.runSymbolTableCreator(NESTMLScopeCreator.java:53)
	at org.nest.frontend.CliConfigurationExecutor.processNestmlModels(CliConfigurationExecutor.java:160)
	at org.nest.frontend.CliConfigurationExecutor.execute(CliConfigurationExecutor.java:71)
	at org.nest.frontend.NestmlFrontend.executeConfiguration(NestmlFrontend.java:359)
	at org.nest.frontend.NestmlFrontend.start(NestmlFrontend.java:122)
	at org.nest.frontend.NestmlFrontendTest.testModelsFolder(NestmlFrontendTest.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testDryRun(org.nest.frontend.NestmlFrontendTest)  Time elapsed: 0.706 sec  <<< ERROR!
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.nest.nestml._symboltable.NESTMLSymbolTableCreator.visit(NESTMLSymbolTableCreator.java:280)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:984)
	at org.nest.nestml._ast.ASTInputLine.accept(ASTInputLine.java:87)
	at org.nest.nestml._visitor.NESTMLVisitor.traverse(NESTMLVisitor.java:971)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:954)
	at org.nest.nestml._ast.ASTInputBlock.accept(ASTInputBlock.java:73)
	at org.nest.nestml._visitor.NESTMLVisitor.traverse(NESTMLVisitor.java:826)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:791)
	at org.nest.nestml._ast.ASTNeuronTOP.accept(ASTNeuronTOP.java:120)
	at org.nest.nestml._visitor.NESTMLVisitor.traverse(NESTMLVisitor.java:111)
	at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:97)
	at org.nest.nestml._ast.ASTNESTMLCompilationUnitTOP.accept(ASTNESTMLCompilationUnitTOP.java:64)
	at org.nest.nestml._symboltable.NESTMLSymbolTableCreator.createFromAST(NESTMLSymbolTableCreator.java:66)
	at org.nest.nestml._symboltable.NESTMLScopeCreator.runSymbolTableCreator(NESTMLScopeCreator.java:53)
	at org.nest.frontend.CliConfigurationExecutor.processNestmlModels(CliConfigurationExecutor.java:160)
	at org.nest.frontend.CliConfigurationExecutor.execute(CliConfigurationExecutor.java:71)
	at org.nest.frontend.NestmlFrontend.executeConfiguration(NestmlFrontend.java:359)
	at org.nest.frontend.NestmlFrontend.start(NestmlFrontend.java:122)
	at org.nest.frontend.NestmlFrontendTest.testDryRun(NestmlFrontendTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by DimitriPlotnikov** [comment] 2017-10-09 10:32
Ok, I reworked Dockerfiles a bit. 

Now, the development version is indicated `--from_sources`. It also invalidates the cache and forces to rebuild the sources.

I tried it in a clean environment and still get correct simulation results from all 3 models (nest, nestml_neuron, nestml_implicit). 

Could you elaborate more on how you are starting and executing NESTML? For the completness how I was working with it:

Fresh clone or updated version of the nestml repository (being in `$nestml_repo/docker` is assumed).
```
./nestml_docker.sh provision --from_sources
./nestml_docker.sh run ../models --from_sources
```

**Comment by vogdb** [comment] 2017-12-21 11:02
@mschmidt87 Possibly the solution to #396 can help you. Just use python2.7. Also I highly recommend to use virtualenvs for that.

**Comment by clinssen** [comment] 2018-12-10 14:08
Closing this issue as it is reported as solved.

**Closed by clinssen** 2018-12-10 14:08 UTC
