### ISSUE TITLE
Errors when running test models

### ISSUE THREAD

**Issue by TomBugnon** [nest/nestml#417] opened 2018-06-01 21:44 UTC
Hello,

I tried installing pynestML (both the `master` and `pynestml` branches)  in a virtualenv using the following commands:
```
python3 setup.py install --prefix=/Users/Tom/.virtualenvs/nestml/
pip3 install -r requirements.py
```
The tests run well except a warning saying that PyGSL is not available. However I run into errors when trying to generate some of the test models.

Some of the models (hh_psc_alpha, izhikevich, ...) give me type errors.
```
python3 pynesTML.py -path models/izhikevich_psc_alpha.nestml -target ../nestml-testdir
Warning: PyGSL is not available. The stiffness test will be skipped.
Warning: No module named 'pygsl'


Generates code for the neuron izhikevich_psc_alpha.
Validating input...
Analyzing shapes...
  I_syn_in is a linear homogeneous ODE
  I_syn_ex is a linear homogeneous ODE
Only shapes provided. Return ODE representation with IV.
Generates code for the neuron izhikevich_psc_alpha_implicit.
[35,izhikevich_psc_alpha_implicit, ERROR, <ADDED_BY_SOLVER>]: Actual type different from expected. Expected: 'pA', got: 'integer'!
[36,izhikevich_psc_alpha_implicit, ERROR, <ADDED_BY_SOLVER>]: Actual type different from expected. Expected: 'pA / ms', got: 'integer'!
[37,izhikevich_psc_alpha_implicit, ERROR, <ADDED_BY_SOLVER>]: Actual type different from expected. Expected: 'pA', got: 'integer'!
[38,izhikevich_psc_alpha_implicit, ERROR, <ADDED_BY_SOLVER>]: Actual type different from expected. Expected: 'pA / ms', got: 'integer'!
```

The ht_neuron model gives me other errors (it seems the syntax is not recognized)
```
python3 pynesTML.py -path models/ht_neuron.nestml -target ../nestml-testdir
Warning: PyGSL is not available. The stiffness test will be skipped.
Warning: No module named 'pygsl'


[13,ht_neuron_nestml, ERROR, [87:16;87:16]]: Variable 'I_Na' used before declaration!
[14,ht_neuron_nestml, ERROR, [87:23;87:23]]: Variable 'I_K' used before declaration!
[31,ht_neuron_nestml, ERROR, [55:4;55:4]]: Function variable 'g_AMPA' has no right-hand side!
[32,ht_neuron_nestml, ERROR, [55:4;55:4]]: Initial value of ode variable 'g_AMPA' not provided!
[33,ht_neuron_nestml, ERROR, [55:12;55:12]]: Function variable 'g_NMDA' has no right-hand side!
[34,ht_neuron_nestml, ERROR, [55:12;55:12]]: Initial value of ode variable 'g_NMDA' not provided!
[35,ht_neuron_nestml, ERROR, [55:20;55:20]]: Function variable 'g_GABAA' has no right-hand side!
[36,ht_neuron_nestml, ERROR, [55:20;55:20]]: Initial value of ode variable 'g_GABAA' not provided!
[37,ht_neuron_nestml, ERROR, [55:29;55:29]]: Function variable 'g_GABAB' has no right-hand side!
[38,ht_neuron_nestml, ERROR, [55:29;55:29]]: Initial value of ode variable 'g_GABAB' not provided!
[39,ht_neuron_nestml, ERROR, [55:38;55:38]]: Function variable 'IKNa_D' has no right-hand side!
[40,ht_neuron_nestml, ERROR, [55:38;55:38]]: Initial value of ode variable 'IKNa_D' not provided!
[41,ht_neuron_nestml, ERROR, [55:46;55:46]]: Function variable 'IT_m' has no right-hand side!
[42,ht_neuron_nestml, ERROR, [55:46;55:46]]: Initial value of ode variable 'IT_m' not provided!
[43,ht_neuron_nestml, ERROR, [55:52;55:52]]: Function variable 'IT_h' has no right-hand side!
[44,ht_neuron_nestml, ERROR, [55:52;55:52]]: Initial value of ode variable 'IT_h' not provided!
[45,ht_neuron_nestml, ERROR, [55:58;55:58]]: Function variable 'Ih_m' has no right-hand side!
[46,ht_neuron_nestml, ERROR, [55:58;55:58]]: Initial value of ode variable 'Ih_m' not provided!
[47,ht_neuron_nestml, ERROR, [56:4;56:10]]: Function variable 'g_AMPA__d' has no right-hand side!
[48,ht_neuron_nestml, ERROR, [56:4;56:10]]: Initial value of ode variable 'g_AMPA__d' not provided!
[49,ht_neuron_nestml, ERROR, [56:13;56:19]]: Function variable 'g_NMDA__d' has no right-hand side!
[50,ht_neuron_nestml, ERROR, [56:13;56:19]]: Initial value of ode variable 'g_NMDA__d' not provided!
[51,ht_neuron_nestml, ERROR, [56:22;56:29]]: Function variable 'g_GABAA__d' has no right-hand side!
[52,ht_neuron_nestml, ERROR, [56:22;56:29]]: Initial value of ode variable 'g_GABAA__d' not provided!
[53,ht_neuron_nestml, ERROR, [56:32;56:39]]: Function variable 'g_GABAB__d' has no right-hand side!
[54,ht_neuron_nestml, ERROR, [56:32;56:39]]: Initial value of ode variable 'g_GABAB__d' not provided!
```

Am I doing something wrong? Are we supposed to use the java/docker releases of nestML (which I have trouble installing)?
Thanks,
Tom

**Comment by kperun** [comment] 2018-06-03 09:07
@TomBugnon Hallo Tom,
the first problem is related to the underlying ODE toolbox, which disregards physical units and operates only in reals and ints. The second problem originates from incomplete models / too strict context conditions. 
Those are not errors in PyNestML itself, but rather related to the used models and other libs. 
To avoid them, use the -dev option (as mentioned in the readme, this should generate code even though errors have been found). All models provided with the code should work fine. 

Best regards,
Konstantin

**Comment by kperun** [comment] 2018-06-04 21:00
@TomBugnon 
Hallo Tom,
sorry for the misunderstanding. With the active -dev option, the errors are still reported but ignored, thus nest code is generated. Consequently, if you use -dev, it should generate code which will work fine (if  you used the models from the models dir, which were tested by us). I think your -path argument may somehow be wrong or pointing somewhere else. Try it without -path ..., this should create a new target dir with in PyNestML's root with the respective model.
While all models result in correct code, the problem is that there are defined according to the old Java implementation, where some context conditions were less strict (thus errors not reported and never fixed). We will fix the models later on, but with the -dev option they already result in valid code.
Regarding the part with pygsl, I thinks this is related to the ODE toolbox. I will test it later on.

Best regards,
Konstantin

**Comment by TomBugnon** [comment] 2018-06-04 23:08
I think you meant the -target option. Actually, a directory is indeed created when using the -dev option, but I couldn't find it at first because it is created one directory above the current dir when not specifying -target, and one directory above where I expected to find it when giving a relative path. The target dir appears where expected when giving a absolute path.
I don't know if this is expected behavior, let me know if I should create a separate issue.
Thanks, T

**Comment by kperun** [comment] 2018-06-05 09:33
@TomBugnon You are right, I was talking about the -target parameter.
Regarding the path issue: This is not a bug and works as intended. Its obvious that if you provide an absolute path that it works as intended ( the path is unambiguous). If you provide a relative one, the directory in which PyNestML.py is located, is selected as root. Thus, if you try to use -path ../target, then it will try to create a target dir in PyNestML parent dir (so the dir in which a subdir for pynestml is located). If you want to have your target dir next to the models dir, just provide -target /target (or without '/' ) as an argument, this should work fine.    
Regards, 
Konstantin

**Comment by TomBugnon** [comment] 2018-06-06 19:08
Sorry if I didn't make myself clear: the directory that seems to be selected as root is neither the directory where PyNestML.py is located, nor the current working directory, but the parent directory of the working directory! This looks like abnormal behavior.
For example, if I launch the script from the directory in which the repository is located (that is, one level above PyNestML.py):

```
$ ls
nestml-PyNestML

$ python3 nestml-PyNestML/PyNestML.py -path nestml-PyNestML/models/aeif_cond_alpha.nestml -dev
... [Code runs with errors]

$ ls # The target dir is not created in the working directory... (as I expected)
nestml-PyNestML

$ ls nestml-PyNestML #..Nor in the directory where the script is located (as you said)
LICENSE  PyNESTML.egg-info  PyNestML.py  README.md  build  dist  doc  models  pynestml  requirements.txt  setup.py  tools

$ ls .. # But in the directory parent to the working directory
pynestml_testdir  target
```

**Comment by kperun** [comment] 2018-06-06 19:20
I just tested it and you are right. I think this is related to python's handling of the current working dir. It will be fixed in one of the next releases. Many thanks for pointing it out.
Best Regards,
Konstantin

**Comment by kperun** [comment] 2018-06-22 09:46
@TomBugnon Both issues have been fixed in the latest merge.

**Closed by kperun** 2018-06-22 09:46 UTC
Labels: bug
