### ISSUE TITLE
NESTML using docker

### ISSUE THREAD

**Issue by claudiacasellato** [nest/nestml#416] opened 2018-05-25 15:33 UTC
Hello
I manage to do ./nestml_docker.sh provision, but with sudo. Otherwise I get "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"
by "sudo docker images"  I check there is "nestml_release      latest "
Then, I try "sudo ./nestml_docker.sh run /home/claudia/workspace/nestml/models"
but I get
"Running docker image 'nestml_release'
adduser: uid '0' in use
sudo: unknown user: nestml
sudo: unable to initialize policy plugin
"

Can you help me please?!

thanks!!

**Comment by claudiacasellato** [comment] 2018-05-25 15:47
I have used docker-engine_1.12.5_cs5-0_ubuntu-trusty_amd64.deb

**Comment by DimitriPlotnikov** [comment] 2018-05-29 12:44
@claudiacasellato Try it again. We updated NestML to PyNestML which works without docker.

**Comment by claudiacasellato** [comment] 2018-06-11 13:15
I was trying  , with git clone https://github.com/nest/nestml/tree/PyNestML
but I get 
Cloning into 'PyNestML'...
fatal: repository 'https://github.com/nest/nestml/tree/PyNestML/' not found

Could you help me, pls?

thanks!!

**Comment by DimitriPlotnikov** [comment] 2018-06-11 13:36
i merged this brach in meanwhile into master.

**Comment by claudiacasellato** [comment] 2018-06-11 14:43
ok thanks, I did "git clone... " , it worked
but then, in doing 
python PyNestML.py -path /home/claudia/workspace/nestml/models -target /home/claudia/workspace/nestml/models/build

I get error,and no folder /build within /nestml/models is created

"
Warning: PyGSL is not available. The stiffness test will be skipped.
Warning: No module named pygsl.odeiv

Traceback (most recent call last):
  File "PyNestML.py", line 22, in <module>
    from pynestml.frontend.pynestml_frontend import main
  File "/home/claudia/workspace/nestml/pynestml/frontend/pynestml_frontend.py", line 25, in <module>
    from pynestml.codegeneration.nest_codegeneration import analyse_and_generate_neurons, generate_nest_module_code
  File "/home/claudia/workspace/nestml/pynestml/codegeneration/nest_codegeneration.py", line 66, in <module>
    template_neuron_h_file = env.get_template('NeuronHeader.jinja2')
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/claudia/workspace/nestml/pynestml/codegeneration/resources_NEST/NeuronHeader.jinja2", line 296, in template
    {% with variable = odeAlias -%}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'with'. Jinja was looking for the following tags: 'endfilter'. The innermost block that needs to be closed is 'filter'.
"

**Comment by DimitriPlotnikov** [comment] 2018-06-11 14:50
@kperun Can you take a look on this, please?

**Comment by kperun** [comment] 2018-06-11 18:16
@DimitriPlotnikov @claudiacasellato I will take a look at this issue. It looks something went during the merging process.

**Comment by DimitriPlotnikov** [comment] 2018-06-11 19:37
@kperun It can be one explanation. However, ci seems to be satisfied with the current code base:
cf. https://travis-ci.org/nest/nestml

**Comment by kperun** [comment] 2018-06-11 20:39
@DimitriPlotnikov Yes, you are completely right. Since travis completes all tests without any issues, the code itself should be correct. @claudiacasellato which version of python do you use? Is your version of PyNestML up to date? 
The code snippet which is reported to be broken is actually correct:
```
    {% for odeAlias in neuron.get_ode_aliases() -%}{% filter indent(4,True) -%}
      {% with variable = odeAlias -%}
      {% include 'directives/MemberDeclaration.jinja2' -%}
      {% endwith -%}{% endfilter -%}
    {% endfor %}
```
All filters and directives are closed correctly.

**Comment by claudiacasellato** [comment] 2018-06-12 13:51
hi 
python: i'm using 2.7.14 ...  and about PyNestML , I have just done "git clone https://github.com/nest/nestml"....

**Comment by kperun** [comment] 2018-06-13 08:42
@claudiacasellato I will try to figure out what is going wrong. In the meantime, could you try to clone it once more somewhere else? Which version of Jinja2 are you using (or did you use the requirements.txt to install the requirements)?

**Comment by DimitriPlotnikov** [comment] 2018-06-13 14:47
no, docker is an isolated container that encapsulates nestml even in a different operating system.

**Comment by kperun** [comment] 2018-06-13 16:40
@AliceGem NestML uses Java as the underlying platform, while PyNestML is based on python. Those are two different platforms, so you don't have to worry that something might get broken by installing pynestml. Moreover, PyNestML does not use docker, so it won't cause any changes to your existing docker installation (in addition to what @DimitriPlotnikov already mentioned). 
I would really appreciate it if you could try to install it.
Regards,
Konstantin

**Comment by AliceGem** [comment] 2018-06-14 10:56
Thanks @DimitriPlotnikov and @kperun !! I launched the PyNESTML installation files: for the python2 setup control, from the PyNESTML.py launching I get _ImportError: No module named astropy.units.core_ ; I have run the setup file obtaining everything ok except _AttributeError: 'module' object has no attribute 'nest_codegenerator_test'_ and from the requirements.txt file running I get a lot of InsecurePlatformWarnings!

**Comment by kperun** [comment] 2018-06-14 15:05
@AliceGem Before executing 
```
python2 setup install --user
```
have you installed all requirements from the requirements.txt via
```
pip2 install -r requirements.txt
```
The problem with astropy seems to be related to this, since parts of astropy (which we use to handle physical units)  are not available. 
Which OS are you using? The problem with InsecurePlatformWarning seems to be rather odd.

**Comment by AliceGem** [comment] 2018-06-14 15:40
Ok, I managed to install the requirements properly (I had to run with sudo rights, otherwise it did not install astropy properly). And also `python2 setup install --user ` is running with no errors, but when launching` python2 setup.py test` I get the same error as @claudiacasellato :

jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'with'. Jinja was looking for the following tags: 'endfilter'. The innermost block that needs to be closed is 'filter'.

(Yes right, the OS version I'm using is too old, it's Ubuntu 14.04.. updating could solve the InsecurePlatform problem)

**Comment by kperun** [comment] 2018-06-17 10:17
@AliceGem I will try to find a solution to this problem. It seems that somehow, the "with" tag is not supported. Now, you are using Ubuntu 14, by any chance, @claudiacasellato , do you also use this OS (or even an older version). Either the templates are really broken (which should actually be reported by Travis and all the tests), or this is somehow related to your OS and perhaps an older version of Jinja2, where the "with" tag was not included. Anyhow, I will set up a new test environment to perform a clean install of PyNestML and check out if it is really not related to the templates.

**Comment by DimitriPlotnikov** [comment] 2018-06-17 10:21
@kperun Or you can even create a new docker image with pynestml.

**Comment by AliceGem** [comment] 2018-06-20 17:04
Hi! @claudiacasellato has the same OS.. we could update the OS if the problem is not fixed, but meanwhile we went back to the docker installation, fixed the previous error , but now, after running `./nestml_docker.sh provision` we get:
INFO: Finished parsing nestml mdoels...
Exception in thread "main" java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135)
at org.nest.nestml._symboltable.NESTMLSymbolTableCreator.visit(NESTMLSymbolTableCreator.java:280)
at org.nest.nestml._visitor.NESTMLVisitor.handle(NESTMLVisitor.java:984)
etc...

**Comment by claudiacasellato** [comment] 2018-06-21 13:09
Yes exactly... it seems a Java problem... but actually it worked on another Desktop PC without Java...

**Comment by kperun** [comment] 2018-06-23 12:47
@claudiacasellato and @AliceGem I have tried to use it on the latest version of Ubuntu (18.04) and it executes without any problems (the python version, without docker). This seems to be related to your systems. If you don't want to update, you can try to use the ISO containing PyNestML as provided here: http://www.nest-simulator.org/download/ (NEW Ubuntu 16.04 Live Media with NEST 2.14.0).

**Comment by AliceGem** [comment] 2018-07-09 10:31
Hi! We have updated to Ubuntu 16.04 but we get the same error related to the _.jinja2_ files. Is it sufficient to run the requirements to have all the tools updated? Or maybe we should update something else to have this error fixed? (On Ubuntu 16.04 it should work right?). Thanks!!!

**Comment by kperun** [comment] 2018-07-09 20:42
@AliceGem  No, it should be sufficient to execute:

`pip2 install -r requirements.txt`

followed by:

`python2 setup install --user`

If everything is fine, python2 setup test should be executable.

**Comment by kperun** [comment] 2018-07-10 10:19
@AliceGem I just integrated a fix into PyNestML. Please try again after pulling the latest version. The installation steps from above still have to be performed.

**Comment by AliceGem** [comment] 2018-07-11 15:50
Hi @kperun, I managed to solve the _jinja2_ problem (that was raised during the execution of the setup test), by upgrading _Jinja2_ version from 2.8 (that was installed in my PC - Ubuntu version 16.04) to 2.10; in this way the `with_` statement was recognized, without generating errors. Then, we could execute the setup test without initial errors, but at the end 2 exceptions were raised: _InvalidPathException: Incorrect path providedresources/CommentTest.nestml_
in file "frontend_configuration.py" during the execution of _test_from_objects_ and _test_from_string_
However PyNESTML is now working and the we managed to create the models from the nestml files.
Thanks!!

**Comment by kperun** [comment] 2018-07-15 13:15
@AliceGem Many thanks for pointing out the issue with Jinja. I never had any problem with it, but it seems some distributions of linux provide it out of the box, but in an older version. The latest version as merged into the master branch fixes this issue and now requires jinja in a version of at least 2.10. The problem with the exception has also been fixed. This was related to some path issues. I will close this issue, if you find new bugs, please open an new issue.

**Closed by kperun** 2018-07-15 13:15 UTC
Labels: bug

**Comment by jougs** [comment] 2018-07-16 07:41
Many thanks to all for their persistence in solving this!
